### ISSUE TITLE
npm vulnerabilities

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/Sitecore.HabitatHome.Omni#64]
Cloned latest master and ran npm install in the fitness/app folder
After the restore the NPM warning shows 63 low vulnerabilities and 1 high.

We should try to have a repo with 0 vulnerabilities reported where/when possible.

**Comment by alexshyba** [comment]
Probably webpack, should be an easy fix, I will take a look.

**Comment by alexshyba** [comment]
@jeanfrancoislarente Submitted PR #65 with the fix.

**Comment by jeanfrancoislarente** [comment]
Closed w/ #65 . Thanks!
